name: im_good
description: A mini demo app for ESD

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  http: ^0.13.4
  dependencies:
  change_app_package_name: ^1.1.0
  sqflite: ^2.0.1
  stacked: ^2.2.7+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

fonts:
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/Ubuntu-Medium.ttf
      - asset: assets/fonts/Ubuntu-Italic.ttf